// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYW4aJDEU5Kw57Bo3SG3_RGUkrICGol7E',
    appId: '1:458477381920:web:9721544721c24f6bc40f45',
    messagingSenderId: '458477381920',
    projectId: 'cs192upclassroomfinder',
    authDomain: 'cs192upclassroomfinder.firebaseapp.com',
    storageBucket: 'cs192upclassroomfinder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04LOXWJN1DSxnw4dbjVbH26WV8DEFm2o',
    appId: '1:458477381920:android:b9f9a680c896e12ac40f45',
    messagingSenderId: '458477381920',
    projectId: 'cs192upclassroomfinder',
    storageBucket: 'cs192upclassroomfinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWb5wJMnAN3qNxgoY2OheE53znIOYl6ug',
    appId: '1:458477381920:ios:574abc86d091705ec40f45',
    messagingSenderId: '458477381920',
    projectId: 'cs192upclassroomfinder',
    storageBucket: 'cs192upclassroomfinder.appspot.com',
    iosBundleId: 'com.example.upClassroomFinderAy2324Cs192',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWb5wJMnAN3qNxgoY2OheE53znIOYl6ug',
    appId: '1:458477381920:ios:574abc86d091705ec40f45',
    messagingSenderId: '458477381920',
    projectId: 'cs192upclassroomfinder',
    storageBucket: 'cs192upclassroomfinder.appspot.com',
    iosBundleId: 'com.example.upClassroomFinderAy2324Cs192',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYW4aJDEU5Kw57Bo3SG3_RGUkrICGol7E',
    appId: '1:458477381920:web:86b7cec3cc15c388c40f45',
    messagingSenderId: '458477381920',
    projectId: 'cs192upclassroomfinder',
    authDomain: 'cs192upclassroomfinder.firebaseapp.com',
    storageBucket: 'cs192upclassroomfinder.appspot.com',
  );
}
